
stages:
  - linting
yaml-lint:
  stage: linting
  #image: ${CONTAINER_REGISTRY}/pipeline-components/yamllint:latest
  image: pipelinecomponents/yamllint:latest
  script:
    - yamllint . --no-warnings
